export const CONTRACT_CONFIG = {
    PROGRAM_ID: "HnoMtMBjarMYksbUdQdqpNYCb9ds43EPtowyh44ADv3J",
    USDT_MINT: "42MMC9srt5Ri5X14GAgXhaHiI3GnPAEERYPJgZJDncDU", // 测试网USDT
    TOKEN_PROGRAM_ID: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
};